// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yviwqfevitaftvcgniqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2aXdxZmV2aXRhZnR2Y2duaXFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMTE2ODUsImV4cCI6MjA2Mzc4NzY4NX0.AMkURgNc9CE9qH166zrYHMuNiAtY6grZUFF_Slh2y6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);